language: node_js
node_js:
  - "8"
sudo: false
cache:
  directories:
    - "node_modules"
script: npm run build
git:
  submodules: true
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master